name: focus_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  percent_indicator: ^4.2.4
  icons_launcher: ^3.0.0
  permission_handler: ^11.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  audioplayers: ^6.2.0
  provider: ^6.1.2
  timezone: ^0.10.0
  android_alarm_manager_plus: ^4.0.7
  flutter_foreground_task: ^8.17.0
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
